"""
Kibana Assets Service

Creates and manages all Kibana-side assets for Search demos:
- Dashboards (P95 latency, query volume, error rates, relevance distribution)
- Slack connector
- Alerting rules (ES|QL threshold)
- Case management connector configuration
- Saved Discover views
- Scoped read-only API key
"""

import json
import logging
import os
import uuid
from typing import Dict, List, Any, Optional
import requests
from elasticsearch import Elasticsearch
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)


class KibanaAssetsService:
    """
    Manages Kibana assets for Search demos via the Kibana REST API.
    All operations are idempotent (tag-based deduplication).
    """

    def __init__(self, es_client: Optional[Elasticsearch] = None):
        self.kibana_url = os.getenv("ELASTICSEARCH_KIBANA_URL", "").rstrip("/")
        self.api_key = os.getenv("ELASTICSEARCH_API_KEY", "")
        self.slack_webhook = os.getenv("SLACK_WEBHOOK_URL", "")
        self.slack_channel = os.getenv("SLACK_CHANNEL", "#elastic-demos")
        self.space_id = os.getenv("KIBANA_SPACE_ID", "default")
        self.es = es_client

        self.headers = {
            "Authorization": f"ApiKey {self.api_key}",
            "Content-Type": "application/json",
        }
        self.write_headers = {**self.headers, "kbn-xsrf": "true"}

    @property
    def _base_url(self) -> str:
        if self.space_id and self.space_id != "default":
            return f"{self.kibana_url}/s/{self.space_id}"
        return self.kibana_url

    # -------------------------------------------------------------------------
    # Dashboard
    # -------------------------------------------------------------------------

    def create_dashboard(
        self,
        demo_slug: str,
        index_names: List[str],
        query_field: str = "query",
        duration_field: str = "response_time_ms",
        error_field: str = "error_code",
        score_field: str = "_score",
        company_name: str = "",
    ) -> Optional[str]:
        """
        Create a Kibana dashboard with four panels:
        1. Query volume over time (bar chart)
        2. P50/P95/P99 response latency (line chart)
        3. Top search terms (table)
        4. Error rate over time (area chart)

        Returns the dashboard ID or None on failure.
        """
        index_pattern = ",".join(index_names)
        title = f"{company_name or demo_slug} — Search Performance Dashboard"
        dashboard_id = str(uuid.uuid4())

        # Build panels using Kibana Lens saved object format
        panels = [
            self._query_volume_panel(index_pattern, query_field),
            self._latency_percentiles_panel(index_pattern, duration_field),
            self._top_search_terms_panel(index_pattern, query_field),
            self._error_rate_panel(index_pattern, error_field),
        ]

        dashboard_so = {
            "attributes": {
                "title": title,
                "description": f"Auto-generated by Elastic Demo Builder for {demo_slug}",
                "panelsJSON": json.dumps(panels),
                "optionsJSON": json.dumps({"useMargins": True, "syncColors": False}),
                "timeRestore": True,
                "timeTo": "now",
                "timeFrom": "now-7d",
                "refreshInterval": {"pause": False, "value": 30000},
                "kibanaSavedObjectMeta": {
                    "searchSourceJSON": json.dumps({
                        "query": {"query": "", "language": "kuery"},
                        "filter": [],
                    })
                },
            },
            "references": [],
        }

        try:
            resp = requests.post(
                f"{self._base_url}/api/saved_objects/dashboard/{dashboard_id}",
                headers=self.write_headers,
                json=dashboard_so,
                timeout=30,
            )
            if resp.status_code in (200, 201):
                logger.info(f"Created dashboard: {title} (id={dashboard_id})")
                return dashboard_id
            logger.warning(f"Dashboard creation returned {resp.status_code}: {resp.text[:300]}")
        except Exception as e:
            logger.warning(f"Could not create dashboard: {e}")

        return None

    def _query_volume_panel(self, index_pattern: str, query_field: str) -> Dict:
        return {
            "gridData": {"x": 0, "y": 0, "w": 24, "h": 15, "i": "panel-1"},
            "version": "8.0.0",
            "type": "lens",
            "panelIndex": "panel-1",
            "embeddableConfig": {
                "title": "Search Query Volume",
                "description": "Number of search queries over time",
                "attributes": {
                    "title": "Search Query Volume",
                    "type": "lens",
                    "visualizationType": "lnsXY",
                    "state": {
                        "datasourceStates": {
                            "formBased": {
                                "layers": {
                                    "layer1": {
                                        "columnOrder": ["col-date", "col-count"],
                                        "columns": {
                                            "col-date": {
                                                "label": "@timestamp",
                                                "dataType": "date",
                                                "operationType": "date_histogram",
                                                "sourceField": "@timestamp",
                                                "params": {"interval": "auto"},
                                            },
                                            "col-count": {
                                                "label": "Query Count",
                                                "dataType": "number",
                                                "operationType": "count",
                                                "isBucketed": False,
                                            },
                                        },
                                    }
                                }
                            }
                        },
                        "visualization": {
                            "layers": [{"layerId": "layer1", "seriesType": "bar_stacked"}],
                            "axisTitlesVisibilitySettings": {"x": True, "yLeft": True},
                        },
                        "query": {"query": "", "language": "kuery"},
                        "filters": [],
                        "index_pattern": {"id": index_pattern},
                    },
                },
            },
        }

    def _latency_percentiles_panel(self, index_pattern: str, duration_field: str) -> Dict:
        return {
            "gridData": {"x": 24, "y": 0, "w": 24, "h": 15, "i": "panel-2"},
            "version": "8.0.0",
            "type": "lens",
            "panelIndex": "panel-2",
            "embeddableConfig": {
                "title": "Response Latency Percentiles (P50 / P95 / P99)",
                "description": "P50, P95 and P99 response times — key SLA indicators",
                "attributes": {
                    "title": "Response Latency Percentiles",
                    "type": "lens",
                    "visualizationType": "lnsXY",
                    "state": {
                        "datasourceStates": {
                            "formBased": {
                                "layers": {
                                    "layer1": {
                                        "columnOrder": [
                                            "col-date",
                                            "col-p50",
                                            "col-p95",
                                            "col-p99",
                                        ],
                                        "columns": {
                                            "col-date": {
                                                "label": "@timestamp",
                                                "dataType": "date",
                                                "operationType": "date_histogram",
                                                "sourceField": "@timestamp",
                                                "params": {"interval": "auto"},
                                            },
                                            "col-p50": {
                                                "label": "P50 Latency (ms)",
                                                "dataType": "number",
                                                "operationType": "percentile",
                                                "sourceField": duration_field,
                                                "params": {"percentile": 50},
                                            },
                                            "col-p95": {
                                                "label": "P95 Latency (ms)",
                                                "dataType": "number",
                                                "operationType": "percentile",
                                                "sourceField": duration_field,
                                                "params": {"percentile": 95},
                                            },
                                            "col-p99": {
                                                "label": "P99 Latency (ms)",
                                                "dataType": "number",
                                                "operationType": "percentile",
                                                "sourceField": duration_field,
                                                "params": {"percentile": 99},
                                            },
                                        },
                                    }
                                }
                            }
                        },
                        "visualization": {
                            "layers": [
                                {
                                    "layerId": "layer1",
                                    "seriesType": "line",
                                    "accessors": ["col-p50", "col-p95", "col-p99"],
                                    "xAccessor": "col-date",
                                }
                            ],
                        },
                        "query": {"query": "", "language": "kuery"},
                        "filters": [],
                    },
                },
            },
        }

    def _top_search_terms_panel(self, index_pattern: str, query_field: str) -> Dict:
        return {
            "gridData": {"x": 0, "y": 15, "w": 24, "h": 15, "i": "panel-3"},
            "version": "8.0.0",
            "type": "lens",
            "panelIndex": "panel-3",
            "embeddableConfig": {
                "title": "Top Search Terms",
                "description": "Most frequently searched queries",
                "attributes": {
                    "title": "Top Search Terms",
                    "type": "lens",
                    "visualizationType": "lnsDatatable",
                    "state": {
                        "datasourceStates": {
                            "formBased": {
                                "layers": {
                                    "layer1": {
                                        "columnOrder": ["col-term", "col-count"],
                                        "columns": {
                                            "col-term": {
                                                "label": "Search Term",
                                                "dataType": "string",
                                                "operationType": "terms",
                                                "sourceField": f"{query_field}.keyword",
                                                "params": {"size": 15, "orderBy": {"type": "column", "columnId": "col-count"}, "orderDirection": "desc"},
                                            },
                                            "col-count": {
                                                "label": "Count",
                                                "dataType": "number",
                                                "operationType": "count",
                                                "isBucketed": False,
                                            },
                                        },
                                    }
                                }
                            }
                        },
                        "visualization": {"columns": [{"columnId": "col-term"}, {"columnId": "col-count"}]},
                        "query": {"query": "", "language": "kuery"},
                        "filters": [],
                    },
                },
            },
        }

    def _error_rate_panel(self, index_pattern: str, error_field: str) -> Dict:
        return {
            "gridData": {"x": 24, "y": 15, "w": 24, "h": 15, "i": "panel-4"},
            "version": "8.0.0",
            "type": "lens",
            "panelIndex": "panel-4",
            "embeddableConfig": {
                "title": "Error Rate Over Time",
                "description": "Tracks failed searches and errors — trigger alerts when this spikes",
                "attributes": {
                    "title": "Error Rate Over Time",
                    "type": "lens",
                    "visualizationType": "lnsXY",
                    "state": {
                        "datasourceStates": {
                            "formBased": {
                                "layers": {
                                    "layer1": {
                                        "columnOrder": ["col-date", "col-errors"],
                                        "columns": {
                                            "col-date": {
                                                "label": "@timestamp",
                                                "dataType": "date",
                                                "operationType": "date_histogram",
                                                "sourceField": "@timestamp",
                                                "params": {"interval": "auto"},
                                            },
                                            "col-errors": {
                                                "label": "Errors",
                                                "dataType": "number",
                                                "operationType": "count",
                                                "filter": {"query": f"{error_field}:* AND NOT {error_field}:200", "language": "kuery"},
                                            },
                                        },
                                    }
                                }
                            }
                        },
                        "visualization": {
                            "layers": [{"layerId": "layer1", "seriesType": "area"}],
                        },
                        "query": {"query": "", "language": "kuery"},
                        "filters": [],
                    },
                },
            },
        }

    # -------------------------------------------------------------------------
    # Slack Connector
    # -------------------------------------------------------------------------

    def ensure_slack_connector(self) -> Optional[str]:
        """
        Create a Kibana Slack webhook connector (deduplicated by name).
        Returns the connector ID or None if Slack not configured.
        """
        if not self.slack_webhook:
            logger.info("SLACK_WEBHOOK_URL not set — skipping Slack connector")
            return None

        connector_name = "Elastic Demo Builder — Slack"

        # Check if already exists
        existing_id = self._find_connector_by_name(connector_name)
        if existing_id:
            logger.info(f"Slack connector already exists: {existing_id}")
            return existing_id

        body = {
            "name": connector_name,
            "connector_type_id": ".slack",
            "config": {},
            "secrets": {"webhookUrl": self.slack_webhook},
        }

        try:
            resp = requests.post(
                f"{self._base_url}/api/actions/connector",
                headers=self.write_headers,
                json=body,
                timeout=30,
            )
            if resp.status_code in (200, 201):
                connector_id = resp.json().get("id")
                logger.info(f"Created Slack connector: {connector_id}")
                return connector_id
            logger.warning(f"Slack connector creation returned {resp.status_code}: {resp.text[:300]}")
        except Exception as e:
            logger.warning(f"Could not create Slack connector: {e}")

        return None

    def _find_connector_by_name(self, name: str) -> Optional[str]:
        try:
            resp = requests.get(
                f"{self._base_url}/api/actions/connectors",
                headers=self.headers,
                timeout=15,
            )
            if resp.status_code == 200:
                for conn in resp.json():
                    if conn.get("name") == name:
                        return conn.get("id")
        except Exception:
            pass
        return None

    # -------------------------------------------------------------------------
    # Alerting Rules
    # -------------------------------------------------------------------------

    def create_alert_rules(
        self,
        demo_slug: str,
        index_names: List[str],
        slack_connector_id: Optional[str],
        duration_field: str = "response_time_ms",
        p95_threshold_ms: int = 2000,
        error_threshold: int = 10,
        company_name: str = "",
    ) -> List[str]:
        """
        Create two alerting rules:
        1. High P95 latency alert (ES|QL threshold)
        2. High error rate alert (ES|QL threshold)

        Returns list of created rule IDs.
        """
        rule_ids = []
        index_pattern = ",".join(index_names)
        actions = []

        if slack_connector_id:
            actions = [
                {
                    "id": slack_connector_id,
                    "group": "threshold met",
                    "params": {
                        "message": (
                            f"🚨 *{company_name or demo_slug} Alert* — "
                            "{{context.message}}\n"
                            f"Index: `{index_pattern}`\n"
                            "Check Kibana for details."
                        )
                    },
                }
            ]

        # Rule 1: High P95 latency
        p95_rule = {
            "name": f"{company_name or demo_slug} — High P95 Search Latency",
            "rule_type_id": ".es-query",
            "consumer": "alerts",
            "schedule": {"interval": "5m"},
            "params": {
                "index": index_names,
                "timeField": "@timestamp",
                "timeWindowSize": 5,
                "timeWindowUnit": "m",
                "thresholdComparator": ">",
                "threshold": [p95_threshold_ms],
                "esQuery": json.dumps({
                    "aggs": {
                        "p95": {
                            "percentiles": {
                                "field": duration_field,
                                "percents": [95],
                            }
                        }
                    },
                    "size": 0,
                }),
            },
            "actions": actions,
            "tags": [demo_slug, "search", "latency", "demo-builder"],
        }

        # Rule 2: High error count
        error_rule = {
            "name": f"{company_name or demo_slug} — High Search Error Rate",
            "rule_type_id": ".es-query",
            "consumer": "alerts",
            "schedule": {"interval": "5m"},
            "params": {
                "index": index_names,
                "timeField": "@timestamp",
                "timeWindowSize": 5,
                "timeWindowUnit": "m",
                "thresholdComparator": ">",
                "threshold": [error_threshold],
                "esQuery": json.dumps({
                    "query": {
                        "bool": {
                            "must_not": [{"term": {"status_code": 200}}],
                            "filter": [{"exists": {"field": "status_code"}}],
                        }
                    },
                    "size": 0,
                }),
            },
            "actions": actions,
            "tags": [demo_slug, "search", "errors", "demo-builder"],
        }

        for rule_body in [p95_rule, error_rule]:
            rule_id = self._create_alert_rule(rule_body)
            if rule_id:
                rule_ids.append(rule_id)

        return rule_ids

    def _create_alert_rule(self, rule_body: Dict[str, Any]) -> Optional[str]:
        try:
            resp = requests.post(
                f"{self._base_url}/api/alerting/rule",
                headers=self.write_headers,
                json=rule_body,
                timeout=30,
            )
            if resp.status_code in (200, 201):
                rule_id = resp.json().get("id")
                logger.info(f"Created alert rule: {rule_body['name']} (id={rule_id})")
                return rule_id
            logger.warning(f"Alert rule creation returned {resp.status_code}: {resp.text[:300]}")
        except Exception as e:
            logger.warning(f"Could not create alert rule '{rule_body.get('name')}': {e}")
        return None

    # -------------------------------------------------------------------------
    # Case Management
    # -------------------------------------------------------------------------

    def configure_case_connector(
        self,
        slack_connector_id: Optional[str],
    ) -> bool:
        """
        Configure Kibana Cases to use the Slack connector as the default
        so that alerts auto-create cases.
        """
        if not slack_connector_id:
            return False

        body = {
            "connector": {
                "id": slack_connector_id,
                "name": "Elastic Demo Builder — Slack",
                "type": ".slack",
                "fields": None,
            },
            "closure_type": "close-by-user",
        }

        try:
            resp = requests.patch(
                f"{self._base_url}/api/cases/configure",
                headers=self.write_headers,
                json=body,
                timeout=30,
            )
            if resp.status_code in (200, 201):
                logger.info("Configured Cases connector")
                return True
            logger.warning(f"Cases config returned {resp.status_code}: {resp.text[:200]}")
        except Exception as e:
            logger.warning(f"Could not configure Cases connector: {e}")

        return False

    # -------------------------------------------------------------------------
    # Data Views (index patterns)
    # -------------------------------------------------------------------------

    def ensure_data_views(
        self,
        index_names: List[str],
    ) -> List[str]:
        """
        Create Kibana Data Views for each index so Discover and dashboards work.
        Idempotent — skips if already exists.
        Returns list of created data view IDs.
        """
        created = []
        for index_name in index_names:
            view_id = self._ensure_data_view(index_name)
            if view_id:
                created.append(view_id)
        return created

    def _ensure_data_view(self, index_name: str) -> Optional[str]:
        if not self.kibana_url:
            return None

        # Check if data view already exists for this index
        try:
            resp = requests.get(
                f"{self._base_url}/api/data_views",
                headers=self.headers,
                timeout=15,
            )
            if resp.status_code == 200:
                for dv in resp.json().get("data_view", []):
                    if dv.get("title", "") in (index_name, f"{index_name}*"):
                        logger.info(f"Data view already exists for: {index_name}")
                        return dv.get("id")
        except Exception:
            pass

        # Create new data view
        body = {
            "data_view": {
                "title": index_name,
                "name": index_name,
                "timeFieldName": "@timestamp",
            }
        }

        try:
            resp = requests.post(
                f"{self._base_url}/api/data_views/data_view",
                headers=self.write_headers,
                json=body,
                timeout=20,
            )
            if resp.status_code in (200, 201):
                view_id = resp.json().get("data_view", {}).get("id")
                logger.info(f"Created data view: {index_name} (id={view_id})")
                return view_id
            logger.warning(f"Data view creation returned {resp.status_code}: {resp.text[:200]}")
        except Exception as e:
            logger.warning(f"Could not create data view for {index_name}: {e}")

        return None

    # -------------------------------------------------------------------------
    # Discover Saved Search
    # -------------------------------------------------------------------------

    def create_discover_view(
        self,
        demo_slug: str,
        index_names: List[str],
        display_fields: List[str],
        company_name: str = "",
    ) -> Optional[str]:
        """
        Create a saved Discover search pre-filtered for demo fields.
        Returns saved search ID or None.
        """
        title = f"{company_name or demo_slug} — Search Explorer"
        search_id = str(uuid.uuid4())

        body = {
            "attributes": {
                "title": title,
                "description": f"Auto-generated by Elastic Demo Builder for {demo_slug}",
                "columns": display_fields[:10],
                "sort": [["@timestamp", "desc"]],
                "kibanaSavedObjectMeta": {
                    "searchSourceJSON": json.dumps({
                        "query": {"query": "", "language": "kuery"},
                        "filter": [],
                        "indexRefName": "kibanaSavedObjectMeta.searchSourceJSON.index",
                    })
                },
            },
            "references": [
                {
                    "name": "kibanaSavedObjectMeta.searchSourceJSON.index",
                    "type": "index-pattern",
                    "id": ",".join(index_names),
                }
            ],
        }

        try:
            resp = requests.post(
                f"{self._base_url}/api/saved_objects/search/{search_id}",
                headers=self.write_headers,
                json=body,
                timeout=30,
            )
            if resp.status_code in (200, 201):
                logger.info(f"Created Discover view: {title} (id={search_id})")
                return search_id
            logger.warning(f"Discover view creation returned {resp.status_code}: {resp.text[:300]}")
        except Exception as e:
            logger.warning(f"Could not create Discover view: {e}")

        return None

    # -------------------------------------------------------------------------
    # Scoped API Key
    # -------------------------------------------------------------------------

    def create_scoped_api_key(
        self,
        demo_slug: str,
        index_names: List[str],
    ) -> Optional[Dict[str, str]]:
        """
        Create a read-only, search-scoped API key for the demo's indices.
        Returns {"id": ..., "encoded": ...} or None.
        """
        if not self.es:
            logger.warning("No ES client — cannot create scoped API key")
            return None

        key_name = f"{demo_slug}-demo-readonly"

        try:
            resp = self.es.security.create_api_key(
                name=key_name,
                role_descriptors={
                    f"{demo_slug}-search-role": {
                        "indices": [
                            {
                                "names": index_names,
                                "privileges": ["read", "view_index_metadata"],
                            }
                        ],
                        "cluster": ["monitor"],
                    }
                },
                expiration="30d",
            )
            logger.info(f"Created scoped API key: {key_name}")
            return {"id": resp["id"], "encoded": resp["encoded"]}
        except Exception as e:
            logger.warning(f"Could not create scoped API key: {e}")
            return None

    # -------------------------------------------------------------------------
    # Teardown
    # -------------------------------------------------------------------------

    def teardown_demo_assets(
        self,
        dashboard_ids: List[str],
        alert_rule_ids: List[str],
        discover_view_ids: List[str],
        scoped_api_key_id: Optional[str],
    ) -> None:
        """Remove all Kibana assets created for a demo."""
        for so_id in dashboard_ids:
            self._delete_saved_object("dashboard", so_id)
        for so_id in discover_view_ids:
            self._delete_saved_object("search", so_id)
        for rule_id in alert_rule_ids:
            self._delete_alert_rule(rule_id)
        if scoped_api_key_id and self.es:
            try:
                self.es.security.invalidate_api_key(ids=[scoped_api_key_id])
                logger.info(f"Invalidated API key: {scoped_api_key_id}")
            except Exception:
                pass

    def _delete_saved_object(self, so_type: str, so_id: str) -> None:
        try:
            resp = requests.delete(
                f"{self._base_url}/api/saved_objects/{so_type}/{so_id}",
                headers=self.write_headers,
                timeout=15,
            )
            if resp.status_code in (200, 204):
                logger.info(f"Deleted {so_type}: {so_id}")
        except Exception:
            pass

    def _delete_alert_rule(self, rule_id: str) -> None:
        try:
            resp = requests.delete(
                f"{self._base_url}/api/alerting/rule/{rule_id}",
                headers=self.write_headers,
                timeout=15,
            )
            if resp.status_code in (200, 204):
                logger.info(f"Deleted alert rule: {rule_id}")
        except Exception:
            pass
