"""
LLM-Driven Demo Orchestrator
Uses LLM to dynamically generate custom data and queries for each demo
"""

import streamlit as st
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
import pandas as pd
import json
import logging
from datetime import datetime
import re
import ast

logger = logging.getLogger(__name__)


@dataclass
class LLMGeneratedDemo:
    """Demo package generated by LLM"""
    demo_id: str
    customer_context: Dict[str, Any]
    data_generation_code: str
    datasets: Dict[str, pd.DataFrame]
    esql_queries: List[Dict[str, str]]
    agent_config: Dict[str, Any]
    demo_guide: str
    aha_moment: Optional[Dict[str, Any]]


class LLMDrivenOrchestrator:
    """Orchestrates demo generation using LLM for dynamic content creation"""

    def __init__(self, llm_client=None):
        """Initialize with LLM client"""
        self.llm_client = llm_client or self._create_default_client()

    def _create_default_client(self):
        """Create default LLM client based on available API keys"""
        from src.services.llm_proxy_service import UnifiedLLMClient
        
        # Use unified client that auto-detects proxy/anthropic/openai
        client = UnifiedLLMClient()
        
        if not client._proxy_client.is_available():
            return None  # Mock mode
        
        return client

    def generate_demo(
        self,
        context: Dict[str, Any],
        progress_callback: Optional[callable] = None
    ) -> LLMGeneratedDemo:
        """Generate complete demo using LLM for custom content"""

        demo_id = f"DEMO-{datetime.now().strftime('%Y%m%d%H%M%S')}"

        # Step 1: Ask LLM to generate custom data generation code
        if progress_callback:
            progress_callback(0.2, "🤖 Generating custom data schema...")

        data_gen_code = self._generate_data_code(context)

        if progress_callback:
            progress_callback(0.4, "📊 Creating datasets...")

        # Step 2: Execute the generated code to create datasets
        datasets = self._execute_data_generation(data_gen_code)

        if progress_callback:
            progress_callback(0.6, "🔍 Generating ES|QL queries...")

        # Step 3: Ask LLM to generate ES|QL queries specific to the use case
        esql_queries = self._generate_esql_queries(context, datasets)

        if progress_callback:
            progress_callback(0.8, "🎯 Creating A-ha moment...")

        # Step 4: Generate A-ha moment
        aha_moment = self._generate_aha_moment(context, datasets, esql_queries)

        if progress_callback:
            progress_callback(0.9, "📝 Writing demo guide...")

        # Step 5: Generate comprehensive demo guide
        demo_guide = self._generate_demo_guide(context, datasets, esql_queries, aha_moment)

        # Step 6: Create agent configuration
        agent_config = self._generate_agent_config(context, esql_queries)

        if progress_callback:
            progress_callback(1.0, "✅ Demo ready!")

        return LLMGeneratedDemo(
            demo_id=demo_id,
            customer_context=context,
            data_generation_code=data_gen_code,
            datasets=datasets,
            esql_queries=esql_queries,
            agent_config=agent_config,
            demo_guide=demo_guide,
            aha_moment=aha_moment
        )

    def _generate_data_code(self, context: Dict[str, Any]) -> str:
        """Ask LLM to generate custom data generation code"""

        prompt = f"""Generate Python code to create realistic synthetic datasets for this customer:

Company: {context.get('company_name')}
Department: {context.get('department')}
Industry: {context.get('industry')}
Pain Points: {', '.join(context.get('pain_points', []))}
Use Cases: {', '.join(context.get('use_cases', []))}
Scale: {context.get('scale')}

Requirements:
1. Create pandas DataFrames that are SPECIFIC to their business
2. Include realistic column names and data patterns for their industry
3. Create relationships between datasets (foreign keys)
4. Include some anomalies or patterns that demonstrate their pain points
5. Use numpy and pandas for generation (already imported)
6. Return a dictionary called 'datasets' with DataFrame names as keys

Example structure:
```python
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Generate main dataset
{context.get('company_name', 'company').lower().replace(' ', '_')}_data = pd.DataFrame({{
    # Custom columns specific to their business
}})

datasets = {{
    'dataset_name': dataframe,
    ...
}}
```

Generate code that creates datasets specifically for {context.get('company_name')}'s {context.get('department')} team:"""

        if self.llm_client:
            # Real LLM call
            if hasattr(self.llm_client, 'messages'):  # Anthropic
                response = self.llm_client.messages.create(
                    model="claude-sonnet-4-5-20250929",
                    max_tokens=2000,
                    temperature=0.7,
                    messages=[{"role": "user", "content": prompt}]
                )
                code = response.content[0].text
            elif hasattr(self.llm_client, 'chat'):  # OpenAI
                response = self.llm_client.chat.completions.create(
                    model="gpt-4",
                    messages=[{"role": "user", "content": prompt}]
                )
                code = response.choices[0].message.content
            else:
                code = self._generate_mock_data_code(context)
        else:
            code = self._generate_mock_data_code(context)

        # Extract just the Python code
        if "```python" in code:
            code = code.split("```python")[1].split("```")[0]

        return code

    def _generate_mock_data_code(self, context: Dict[str, Any]) -> str:
        """Generate mock data code for testing"""
        company = context.get('company_name', 'Company').lower().replace(' ', '_')

        return f"""import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Customer data specific to {context.get('company_name')}
customers = pd.DataFrame({{
    'customer_id': [f'CUST-{{i:06d}}' for i in range(1000)],
    'company_name': [f'Customer {{i}}' for i in range(1000)],
    'segment': np.random.choice(['Enterprise', 'SMB', 'Startup'], 1000),
    'lifetime_value': np.random.lognormal(10, 2, 1000),
    'churn_risk': np.random.beta(2, 5, 1000)
}})

# Transactions
transactions = pd.DataFrame({{
    'transaction_id': [f'TXN-{{i:08d}}' for i in range(10000)],
    'customer_id': np.random.choice(customers['customer_id'], 10000),
    'amount': np.random.lognormal(5, 1.5, 10000),
    'timestamp': pd.date_range(end=datetime.now(), periods=10000, freq='H'),
    'status': np.random.choice(['completed', 'pending', 'failed'], 10000, p=[0.8, 0.15, 0.05])
}})

datasets = {{
    '{company}_customers': customers,
    '{company}_transactions': transactions
}}"""

    def _execute_data_generation(self, code: str) -> Dict[str, pd.DataFrame]:
        """Execute the generated code to create datasets"""
        try:
            # Create a safe namespace for execution
            namespace = {
                'pd': pd,
                'np': np,
                'datetime': datetime,
                'timedelta': timedelta
            }

            # Execute the code
            exec(code, namespace)

            # Extract the datasets
            if 'datasets' in namespace:
                return namespace['datasets']
            else:
                logger.warning("No 'datasets' variable found in generated code")
                return {}

        except Exception as e:
            logger.error(f"Error executing generated data code: {e}")
            # Return minimal fallback data
            return {
                'fallback_data': pd.DataFrame({
                    'id': range(100),
                    'value': np.random.random(100)
                })
            }

    def _generate_esql_queries(
        self,
        context: Dict[str, Any],
        datasets: Dict[str, pd.DataFrame]
    ) -> List[Dict[str, str]]:
        """Ask LLM to generate ES|QL queries specific to the use case"""

        # Get dataset schemas
        schemas = {}
        for name, df in datasets.items():
            schemas[name] = {
                'columns': list(df.columns),
                'types': df.dtypes.to_dict(),
                'sample_row': df.iloc[0].to_dict() if len(df) > 0 else {}
            }

        prompt = f"""Generate ES|QL queries for this customer's specific needs:

Company: {context.get('company_name')}
Department: {context.get('department')}
Pain Points: {', '.join(context.get('pain_points', []))}
Use Cases: {', '.join(context.get('use_cases', []))}

Available datasets:
{json.dumps(schemas, indent=2, default=str)}

Generate 5-8 ES|QL queries that:
1. Directly address their pain points
2. Show the value of real-time analytics
3. Progress from simple to complex
4. Include at least one JOIN if multiple datasets exist
5. Include calculations relevant to their business

Format each query as:
```json
[
  {{
    "name": "Query Name",
    "description": "What this shows",
    "esql": "FROM dataset | ...",
    "expected_insight": "What they'll learn"
  }},
  ...
]
```

Generate queries that will make {context.get('company_name')} say "This solves our exact problem!":"""

        if self.llm_client:
            # Real LLM call
            if hasattr(self.llm_client, 'messages'):  # Anthropic
                response = self.llm_client.messages.create(
                    model="claude-sonnet-4-5-20250929",
                    max_tokens=2000,
                    temperature=0.7,
                    messages=[{"role": "user", "content": prompt}]
                )
                content = response.content[0].text
            elif hasattr(self.llm_client, 'chat'):  # OpenAI
                response = self.llm_client.chat.completions.create(
                    model="gpt-4",
                    messages=[{"role": "user", "content": prompt}]
                )
                content = response.choices[0].message.content
            else:
                return self._generate_mock_queries(datasets)
        else:
            return self._generate_mock_queries(datasets)

        # Parse JSON from response
        try:
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0]
            queries = json.loads(content)
            return queries
        except:
            return self._generate_mock_queries(datasets)

    def _generate_mock_queries(self, datasets: Dict[str, pd.DataFrame]) -> List[Dict[str, str]]:
        """Generate mock queries for testing"""
        dataset_names = list(datasets.keys())
        first_dataset = dataset_names[0] if dataset_names else "data"

        return [
            {
                "name": "Overview Dashboard",
                "description": "High-level metrics",
                "esql": f"FROM {first_dataset} | STATS count = COUNT(*), avg = AVG(value)",
                "expected_insight": "Overall system health"
            },
            {
                "name": "Trend Analysis",
                "description": "Patterns over time",
                "esql": f"FROM {first_dataset} | EVAL day = DATE_TRUNC(1 day, timestamp) | STATS daily_count = COUNT(*) BY day",
                "expected_insight": "Usage patterns"
            }
        ]

    def _generate_aha_moment(
        self,
        context: Dict[str, Any],
        datasets: Dict[str, pd.DataFrame],
        queries: List[Dict[str, str]]
    ) -> Dict[str, Any]:
        """Generate the A-ha moment that will wow the customer"""

        prompt = f"""Create an "A-ha moment" for this demo that will make {context.get('company_name')} immediately see the value:

Their biggest pain point: {context.get('pain_points', ['Unknown'])[0]}
Their goal: {context.get('use_cases', ['Analytics'])[0]}

The A-ha moment should:
1. Show a dramatic improvement (e.g., "6 hours → 3 seconds")
2. Reveal a hidden insight in their data
3. Demonstrate solving their exact pain point
4. Be visually impactful

Provide:
- The setup (what to show first)
- The reveal (the wow moment)
- The impact statement (what this means for them)
- A specific ES|QL query that demonstrates this

Return as JSON with keys: setup, reveal, impact, query"""

        if self.llm_client:
            # Generate with LLM
            # ... LLM call ...
            pass

        # Mock for now
        return {
            "setup": "First, let me show you how long your current process takes...",
            "reveal": "Now watch this - the same analysis in 2 seconds!",
            "impact": "This means your team saves 40 hours per week",
            "query": queries[0]["esql"] if queries else "FROM data | STATS instant_insight = COUNT(*)"
        }

    def _generate_demo_guide(
        self,
        context: Dict[str, Any],
        datasets: Dict[str, pd.DataFrame],
        queries: List[Dict[str, str]],
        aha_moment: Dict[str, Any]
    ) -> str:
        """Generate a customized demo guide"""

        prompt = f"""Write a demo guide for showing Elastic Agent Builder to {context.get('company_name')}'s {context.get('department')} team.

Include:
1. Opening hook that references their specific pain points
2. Demo flow that builds to the A-ha moment
3. Specific talk track for each query
4. Objection handling for their industry
5. Clear next steps

Make it conversational and specific to their situation."""

        # For now, return a template
        return f"""# Demo Guide: {context.get('company_name')} - {context.get('department')}

## Opening Hook
"I know you mentioned {context.get('pain_points', ['challenges'])[0]}. Let me show you how other {context.get('industry', 'companies')} companies have solved this..."

## The A-ha Moment
{aha_moment.get('setup', '')}
{aha_moment.get('reveal', '')}
**Impact**: {aha_moment.get('impact', '')}

## Queries to Demo
""" + "\n".join([f"- **{q['name']}**: {q['description']}" for q in queries])

    def _generate_agent_config(
        self,
        context: Dict[str, Any],
        queries: List[Dict[str, str]]
    ) -> Dict[str, Any]:
        """Generate agent configuration"""
        return {
            "name": f"{context.get('company_name', 'Company')} {context.get('department', 'Team')} Assistant",
            "instructions": f"You help {context.get('department', 'the team')} with {', '.join(context.get('use_cases', ['analytics']))}",
            "tools": [
                {
                    "name": q["name"].lower().replace(" ", "_"),
                    "query": q["esql"]
                }
                for q in queries[:5]
            ]
        }